edition = "2024"

# Imports 
imports_granularity = "Module"
merge_imports = true
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments
comment_width = 100
format_code_in_doc_comments = true
wrap_comments = true

# Functions 
brace_style = "PreferSameLine"  
control_brace_style = "AlwaysSameLine"
force_multiline_blocks = true  


# Readability
use_field_init_shorthand = true
where_single_line = false 
newline_style = "Unix"
hard_tabs = true
tab_spaces = 4

